# Copyright 2019 Autodesk, Inc.  All rights reserved.
#
# Use of this software is subject to the terms of the Autodesk license agreement
# provided at the time of installation or download, or which otherwise accompanies
# this software in either electronic or hard copy form.
#

language: python

python:
    - "3.8"

env:
  global:
    - DOC_PATH=""
    - S3_BUCKET=sg-devdocs
    - S3_WEB_URL=http://sg-devdocs.s3-website-us-east-1.amazonaws.com

jobs:
  include:
    # Because the org name is still shotgunsoftware, we deploy to
    # shotgunsoftware.github.io, but target developer.shotgridsoftware.com since
    # that will be our new custom domain.
    - name: developer.shotgridsoftware.com
      env:
        DOC_URL=https://developer.shotgridsoftware.com
        REPO_URL=shotgunsoftware/shotgunsoftware.github.io
        CNAME=developer.shotgridsoftware.com

cache:
  pip: true
  directories:
     # manually cache ruby dependencies
     - $TRAVIS_BUILD_DIR/tk-doc-generator/vendor/bundle

before_install:
  # required dependency for sphinx
  - sudo apt-get install -y pandoc

install:
  #
  # jekyll dependencies
  - bundle install --gemfile=./tk-doc-generator/Gemfile --deployment
  #
  # sphinx dependnecies
  - pip install -r ./tk-doc-generator/requirements.txt

script:
  # script that runs the CI and handles S3 previews
  - python ./tk-doc-generator/travis-generate-docs.py

deploy:
  # When commiting to master, auto-deploy to github-pages
  # This will copy the contents of the _build folder to gh-pages branch and push
- provider: pages
  repo: $REPO_URL
  local-dir: ./_build
  target-branch: master
  verbose: true
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  fqdn: $CNAME
  on:
    # only do this when on the master branch
    branch: master
