name: Generate Preview
on: [pull_request]
jobs:
  Generate-Preview:
    runs-on: ubuntu-latest
    environment: docs-build
    env:
      DOC_PATH:
      S3_BUCKET: sg-devdocs
      S3_WEB_URL: http://sg-devdocs.s3-website-us-east-1.amazonaws.com
      DOC_URL: https://developer.shotgridsoftware.com
      REPO_URL: shotgunsoftware/shotgunsoftware.github.io
      CNAME: developer.shotgridsoftware.com
      PR_NUMBER: ${{ github.event.number }}
    steps:
      - uses: actions/checkout@v2
        with:
          # we need to checkout tk-doc-generator submodule as well.
          submodules: 'true'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Install pandoc
        run: sudo apt-get install -y pandoc
      - name: Install jekyll dependencies
        run: bundle install --gemfile=./tk-doc-generator/Gemfile --deployment
      - name: Install tk-doc-generator requirements
        run: pip install -r ./tk-doc-generator/requirements.txt
      - name: Echo PR_NUMBER
        run: echo $PR_NUMBER
      - name: Generate and publish preview
        run: python ./tk-doc-generator/actions-generate-docs.py
