name: Publish Developer Docs
on:
  push:
    branches:
      - master
jobs:
  Publish-Docs:
    runs-on: ubuntu-latest
    environment: docs-build
    steps:
      - name: Checkout repo and submodules
        uses: actions/checkout@v2
        with:
          # we need to checkout tk-doc-generator submodule as well.
          submodules: 'true'
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Install Pandoc
        run: sudo apt-get install -y pandoc
      - name: Install Jekyll dependencies
        run: bundle install --gemfile=./tk-doc-generator/Gemfile --deployment
      - name: Install tk-doc-generator requirements
        run: pip install -r ./tk-doc-generator/requirements.txt
      - name: Generate HTML
        env:
          DOC_PATH:
          S3_BUCKET: sg-devdocs
          S3_WEB_URL: http://sg-devdocs.s3-website-us-east-1.amazonaws.com
          DOC_URL: https://developer.shotgridsoftware.com
          REPO_URL: shotgunsoftware/shotgunsoftware.github.io
          CNAME: developer.shotgridsoftware.com
          PR_NUMBER: ${{ github.event.number }}
          AWS_S3_ACCESS_KEY: ${{ secrets.AWS_S3_ACCESS_KEY }}
          AWS_S3_ACCESS_TOKEN: ${{ secrets.AWS_S3_ACCESS_TOKEN }}
          TK_GITHUB_TOKEN: ${{ secrets.TK_GITHUB_TOKEN }}
        run: python ./tk-doc-generator/actions-generate-docs.py
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: master
          folder: ./_build
          token: ${{ secrets.TK_GITHUB_TOKEN }}
          repository-name: shotgunsoftware/shotgunsoftware.github.io
          single-commit: true
          clean: true
          clean-exclude: CNAME
